apiVersion: apps/v1
kind: Deployment
metadata:
  name: tinychat
  labels:
    app: tinychat
spec:
  selector:
    matchLabels:
      app: tinychat
  replicas: 1
  template:
    metadata:
      labels:
        app: tinychat
    spec:
      containers:
      - name: tinychat
        image: tinychat:v1.0.0
        imagePullPolicy: Never
        ports:
        - containerPort: 3000
        resources:
            requests:
                cpu: "500m"
            limits:
                cpu: "1000m"
